global:
  dependencies:
    python:
      - forge-sdk==4.0.0a10
      - forge-cli==4.0.0a24
      - cecs==4.0.0a3
      - services/*.py
  env:
    PROJECT_SLUG: 'ava'


    ENVIRONMENT_NAME: {{ env.ENVIRONMENT_NAME }}
    MODULE: '{{ env.MODULE | default("local", True) }}'
    LOG_LEVEL: INFO

    # Messaging
    PULSAR_URL: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650

    # Databases
    MONGO_CLIENT_HOST: mongodb:27017
    MONGO_CLIENT_USERNAME: root

    POSTGRES_CLIENT_HOST: postgresql
    POSTGRES_CLIENT_PORT: '5432'
    POSTGRES_CLIENT_USERNAME: postgres

    REDIS_URL: redis-master:6379

    BACKUP_CONTAINER_NAME: '{{ env.BACKUP_CONTAINER_NAME }}'
    BACKUPS_STORAGE_ACCOUNT_NAME: '{{ env.BACKUPS_STORAGE_ACCOUNT_NAME }}'

    # Misc
    DEFAULT_TIME_ZONE: Europe/Zagreb

  secrets:
    SENTRY_DSN: '{{ env.SENTRY_DSN }}'

    MONGO_CLIENT_PASSWORD: admin
    POSTGRES_CLIENT_PASSWORD: admin

    BACKUPS_STORAGE_ACCOUNT_KEY: '{{ env.BACKUPS_STORAGE_ACCOUNT_KEY }}'
    BACKUPS_ZIP_ENCRYPT: '{{ env.BACKUPS_ZIP_ENCRYPT }}'

  backups:
    mongo:
      enabled: true
      cron: 3 5,17 * * *
    postgres:
      enabled: true
      cron: 8 5,17 * * *
    redis:
      enabled: true
      cron: 13 5,17 * * *

  cecs:
    params: -e venv

  repository: nexus.vingd.net

services:

  rule-engine:
    type: java
    resources:
      cpu: 500m
      memory: 650Mi

  heartbeat-scheduler:
    package: heartbeat
    type: python
    version: 4.0.0a4
    env:
      HEARTBEAT_CYCLE: 30
    db:
      mongo: true
    dependencies:
      - rule-engine-api==4.0.0a20
    resources:
      cpu: 69m
      memory: 65Mi

  heartbeat-sender:
    package: heartbeat
    type: python
    version: 4.0.0a4
    db:
      mongo: true
    dependencies:
      - rule-engine-api==4.0.0a20
    resources:
      cpu: 84m
      memory: 94Mi

  email-adapter:
    type: python
    version: 4.0.0a10
    env:
      PROJECT_EMAIL_NAME: "{{env.PROJECT_EMAIL_NAME}}"
      PROJECT_EMAIL_ADDRESS: "{{env.PROJECT_EMAIL_ADDRESS}}"
      PROJECT_EMAIL_PASSWORD: "{{env.PROJECT_EMAIL_PASSWORD}}"
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      IMAP_SERVER: imap.gmail.com
      IMAP_PORT: 993
    db:
      mongo: true
    resources:
      cpu: 50m
      memory: 75Mi

  email-receiver:
    enabled: false
    type: python
    package: email-adapter
    subservice: email_receiver
    version: 4.0.0a10
    db:
      mongo: true
    resources:
      cpu: 50m
      memory: 75Mi
