global:
  env:
    PULSAR_URL: {{ env.PULSAR_URL }}
    PULSAR_ENDPOINT_URL: {{ env.PULSAR_ENDPOINT_URL }}

    MONGO_CLIENT_HOST: {{ env.MONGO_CLIENT_HOST }}
    MONGO_CLIENT_USERNAME: {{ env.MONGO_CLIENT_USERNAME }}

    POSTGRES_CLIENT_HOST: {{ env.POSTGRES_CLIENT_HOST }}
    POSTGRES_CLIENT_PORT: {{ env.POSTGRES_CLIENT_PORT }}
    POSTGRES_CLIENT_USERNAME: {{ env.POSTGRES_CLIENT_USERNAME }}

    REDIS_CLIENT_HOST: {{ env.REDIS_CLIENT_HOST }}
    REDIS_CLIENT_PORT: {{ env.REDIS_CLIENT_PORT }}

  secrets:
    MONGO_CLIENT_PASSWORD: {{ env.MONGO_CLIENT_PASSWORD }}
    POSTGRES_CLIENT_PASSWORD: {{ env.POSTGRES_CLIENT_PASSWORD }}
    
services:
  mitems:
    env:
      SITE_URL: localhost:8001
    port: 8001

  armory:
    command:
      build: "./build.sh"
      run: "armory-admin runserver"
    env:
      SITE_URL: '{{ env.ARMORY_SITE_URL | default("http://localhost:8000", true) }}'
    port: 8000

  employee-manager:
    port: 8002
