com.mindsmiths.armory.events.UserConnectedEvent:
  - !GetOrCreateAgentByConnection
    connectionName: armory
    connectionField: connectionId
    agentType: agents.Nola
com.mindsmiths.armory.events.SubmitEvent:
  - !GetOrCreateAgentByConnection
    connectionName: armory
    connectionField: connectionId
    agentType: agents.Nola
com.mindsmiths.armory.events.UserDisconnectedEvent:
  - !GetOrCreateAgentByConnection
    connectionName: armory
    connectionField: connectionId
    agentType: agents.Nola
